apiVersion: v1
kind: Service
metadata:
  name: non-root-debian-svc
  labels:
    run: non-root-debian-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: non-root-debian