apiVersion: v1
kind: Service
metadata:
  name: root-debian-svc
  labels:
    run: root-debian-svc
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: root-debian